sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

before_script:
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - bower install -f

script:
  - grunt build:layout1
  
deploy:
  provider: s3
  access_key_id: AKIAJJXJQFDWLOEYXZQQ
  secret_access_key: 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
  bucket: "test-deployment-pba"
